### ISSUE TITLE
Quick flashes of other workspaces when moving the mouse between monitors

### ISSUE THREAD

**Issue by tsemczyszyn** [hyprland-community/pyprland#1]
I just tried this out in order to get the workspace switching behaviour I'm looking for on multi-monitor. I really like this idea of running a side process with plugins.

The only plugin I enabled is workspaces following focus. I noticed that if I move the mouse between the monitors there is sometimes a flickering effect where I briefly see another workspace displayed on the monitor I'm switching to.

If you move the mouse back and forth across the boundary between monitors very quickly it seems to happen more.

**Comment by fdev31** [comment]
Thank you for giving it a try!
It was way worse initially, I have to cut the animations during the transition to mitigate the glitches.
I'll do more tests but I think to have a perfect transition some changes will be needed in hyprland too...
I also need to test with https://github.com/hyprwm/Hyprland/issues/2154 which seems to relate - I'll update this ticket if some progress is made.

**Comment by fdev31** [comment]
Try the very last git version of Hyprland, it fixes the glitches for me, I was even able to remove the workaround which disables animations during transition (I pushed a change just now).
If you can confirm this is fixing it for you too, I'll close this issue.

**Comment by fdev31** [comment]
So it happened to bit an hyprland issue, lot of testing with the latest git version including the fix above showed no more flickering.
Workarounds were removed from pyprland.

**Comment by tsemczyszyn** [comment]
Just had a read through hyprwm/hyprland#2154. Good stuff. My hyprland setup with multiple monitors is at the office so I'll check it out on Monday. Thanks.
