### ISSUE TITLE
Toggle terminal doesnt work in opensuse

### ISSUE THREAD

**Issue by Asteroth2018** [hyprland-community/pyprland#100]
ive got pyprland installed on hyprland in opensuse tumbleweed and ive got it configured to start at startup in my exec files and it does start up normally. Now ive got a keybind set to toggle my kitty terminal but it doesnt work, but when i go to terminal and write pypr toggle term then it works. But that's the only way ive manged to get it working. Zoom alsoo doesnt work but that's an issue for other subject i think.

**Comment by fdev31** [comment]
Try using the full path to pypr see if it fixes something

**Comment by Asteroth2018** [comment]
still doesnt work and in the terminal i get error like this: 
Fail to parse hyprctl version: Expecting value: line 8 column 16 (char 136)

**Comment by Asteroth2018** [comment]
sorry my mistake IT WORKS ACTUALLY!!! THANK YOU!!

**Comment by Asteroth2018** [comment]
Ok it works but at the start of my system i get tiny notification inthe corner tha hyprctl version: incorrect json data. but everything works fine just that notification is ther for few seconds

**Comment by Asteroth2018** [comment]
when i run debug mode this is the error in full:
Fail to parse hyprctl version: Expecting value: line 8 column 16 (char 136) // pyprland.py:18

**Comment by fdev31** [comment]
Check the line 8 of your configuration, there is a syntax error

**Comment by fdev31** [comment]
> when i run debug mode this is the error in full:
> Fail to parse hyprctl version: Expecting value: line 8 column 16 (char 136) // pyprland.py:18

This is a known problem with thumbleweed package
