### ISSUE TITLE
[BUG] magnify: cannot zoom

### ISSUE THREAD

**Issue by dafitt** [hyprland-community/pyprland#105]
**Pyprland version**
Which version did you use? 
Pyprland `2.3.2`
Hyprland `v0.40.0`

**Describe the bug**
I cannot magnify my hyprland deskotp.
Systemd error: `FAILED b'config option <misc:cursor_zoom_factor> does not exist.'`
I think because hyprland has changed the option `misc:cursor_zoom_factor` to `cursor:zoom_factor` in `v0.40.0`

**To Reproduce**
1. `systemctl start --user pyprland.service`
2. `pypr zoom`
3. `systemctl status --user pyprland.service`
5. See error `FAILED b'config option <misc:cursor_zoom_factor> does not exist.'`

**Expected behavior**
`pypr zoom ++0.5` should magnify my desktop.

**Configuration (provide following files/samples when relevant):**

pyprland.toml:

```
[pyprland]
plugins = ["magnify"]
```

**Comment by fdev31** [comment]
Use version 0.40.0 of Hyprland to avoid this issue.
The change only happens in git version.
Looks like it also moved from "misc" to "cursor", I'll try to implement some auto-detection to avoid problems when 0.41 is released, thank you for the report :)

To understand what's going on I checked:

- https://wiki.hyprland.org/0.40.0/Configuring/Variables/#misc
- https://wiki.hyprland.org/Configuring/Variables/#cursor

**Comment by fdev31** [comment]
Are you able to test with your former setup (in case you changed to stable Hyprland) and also use the git version of Pyprland?
It should be fixed on the latest git version.

**Comment by fdev31** [comment]
I installed the git version for testing... and got another challenge calling `hyprctl version -j
`:
```json
{
    "branch": "main",
    "commit": "4e42107d25dc47ee94da282db233f85f1e4c6bd0",
    "dirty": false,
    "commit_message": "pointermgr: ensure compositor exist on destroy (6216)",
    "commit_date": "Thu May 23 21:19:14 2024",
    "tag": "v0.40.0-127-g4e42107d",
    "commits": "4733",
    "flags": []
}
```

Current Pypr code considers this is version 0.40.0.... while it broke compatibility for it.
Are you also using arch / using the same package types? If not, what is the output of this command on your setup?

**Comment by fdev31** [comment]
I'm going to add support for `hyprland_version` in the [pyprland] section, eg:

```toml
[pyprland]
include = ["~/.config/hypr/pyprland.d"]
hyprland_version = "0.41.0"
```

I consider it fixed since I can't find a better solution for those transitioning periods... if you have another (better?) suggestion please re-open.

**Comment by fdev31** [comment]
Need to write docs, also improved things, maybe you'll not need the `hyprland_version` config option...

**Comment by dafitt** [comment]
> Are you able to test with your former setup (in case you changed to stable Hyprland) and also use the git version of Pyprland?
> It should be fixed in the latest git version.

Yes. I am on **NixOS** and I added `pyprland.url = "github:hyprland-community/pyprland";` in _`flake.nix`_ and an overlay `pyprland = inputs.pyprland.packages.${prev.system}.pyprland;`, rebuilt and

Confirmed that magnify is working again! Good work!

---

> Are you also using arch / using the same package types? If not, what is the output of this command on your setup?

Regarding `hyprctl version -j` my output is

```
{
    "branch": "",
    "commit": "2ccd45a84475fab46c6fecd2fe226d3173104743",
    "dirty": true,
    "commit_message": "",
    "commit_date": "2024-05-12",
    "tag": "",
    "commits": "",
    "flags": []
}
```

which seems broken. I think I have read that this is a bug only on NixOS somewhere, but I cannot find the hyprctl issue anymore. But I am currently using the hyprland version on nixpkgs-unstable: `0.40.0-unstable-2024-05-12`

**Comment by dafitt** [comment]
> I consider it fixed since I can't find a better solution for those transitioning periods... if you have another (better?) suggestion please re-open.

Sorry, I cannot really help you with that. I'm still a programming newbie.

**Comment by fdev31** [comment]
Released a new version including it and added a note in the Troubleshooting page!
