### ISSUE TITLE
[FEAT] scratchpads: pypr hide *

### ISSUE THREAD

**Issue by dafitt** [hyprland-community/pyprland#106]
**Is your feature request related to a problem? Please describe.**
I tried scratchpads for the first time and was expecting that ESC would hide any currently open scratchpad.

**Describe the solution you'd like**
I would like to hide all / any scratchpads with one command / keybinding like for example `bind=, escape, exec, pypr hide *`

**Describe alternatives you've considered**
No known alternative, at least i found nothing in the wiki

**Additional context**
`pypr hide` command

**Comment by fdev31** [comment]
I thought about it before, but wasn't sure it would be useful...
About the ESC it can't be done unfortunately, but for the hide "*" it  should be quite easy.
Do you think "show *" also makes sense ?

**Comment by fdev31** [comment]
Are you able to test the latest git version to provide some feedback?
