### ISSUE TITLE
Expose plugin will send windows to special, but will not bring them back.

### ISSUE THREAD

**Issue by krlhBlupine** [hyprland-community/pyprland#11]
Hey! Title mostly covers it- I'm using the AUR version from august first, was testing out the expose plugin. The hotkey I set will send away my windows, but won't return them from the workspace. I have the following in my config JSON:

```{
    "pyprland": {
        "plugins": [
            "scratchpads",
            "expose"
        ]
    },
    "scratchpads": {
        "term": {
            "command": "kitty --class kitty-dropterm",
            "animation": "fromTop",
            "placements": ""
        },
        "files": {
            "command": "dolphin",
            "animation": "fromTop",
            "placements": ""
        }
    },
    "expose": {
        "include_special": true
      }
}
```

and the following command in hypr:
`bind = $mainMod, N, exec, pypr toggle_minimized`

I've also got some debug output attached for you.
[pypr.log](https://github.com/hyprland-community/pyprland/files/12327525/pypr.log)

**Comment by fdev31** [comment]
you mean not ANY window ?
Maybe that's a misunderstanding on how it actually works:

- `toggle_minimized` just toggles the state of the client window
- to view minimized windows, you need a key bound such as
  `bind = $mainMod SHIFT, U, togglespecialworkspace, minimized`
- you can focus a minimized window & toggle minimized state from there

I will update the documentation which is not really informative.

**Comment by krlhBlupine** [comment]
Yep- That fixes the issue, thank you a ton!
