### ISSUE TITLE
[BUG] Import error, possible missing module? 

### ISSUE THREAD

**Issue by Chxshire22** [hyprland-community/pyprland#110]
**Pyprland version**
2.3.7

**Describe the bug**
Import error aiopen from pyprland aioops. 

**To Reproduce**
1. installed the package with curl from https://hyprland-community.github.io/pyprland/
2. set up the pyprland.toml file
3.  run pypr to get the daemon running to test it 

**Expected behavior**

**Configuration (provide following files/samples when relevant):**
- pyprland.toml
not exactly relevant, but the exact toml supplied in the link above and the added the lines to the end of my conf file for the hyprland configs. 

**Additional context**
![swappy-20240609_024232](https://github.com/hyprland-community/pyprland/assets/130922684/7a63eef6-4474-4dac-8692-3099016672b7)

**Comment by fdev31** [comment]
Oh thank you there was a typo!
Note that installing "aiofiles" fixes the issue too...
You can rename substitute aioopen with aiopen to get the same result of the git version which I just patched.
