### ISSUE TITLE
Force-Bound monitor failure mode is unclear

### ISSUE THREAD

**Issue by krlhBlupine** [hyprland-community/pyprland#113]
**Pyprland version**
2.3.7

**Describe the bug**
Failure mode when scratchpad is force-bound to a non-present monitor is unclear. Received an error for 'no monitor is focused' first, then received a 'NoneType is not scriptable' error. I feel like a clearer error message would do some good, and a fallback to the focused monitor might be even better.

**To Reproduce**
```
[pyprland]
plugins = ["scratchpads", "expose"]

[scratchpads.term]
animation = "fromBottom"
command = "kitty --class kitty-dropterm --single-instance"
position = "13% 36%"
# force_monitor = "DP-3"
restore_focus = true


[expose]
include_special = true
```
Uncomment line, (presuming you don't have a 'DP-3'), reload, summon the scratchpad.

**Comment by fdev31** [comment]
Feel free to test the git version & provide some feedback!

**Comment by rgbfireside** [comment]
Apologies for the delay- I'm having some trouble building and testing on NixOS specifically, so I'll get back to you when I have a virtual setup up and running. Just from what I can see in the commit though everything looks good!

**Comment by krlhBlupine** [comment]
Hey! Apologies for the delay, I'm having some trouble building on NixOS specifically. I can get back to you when I actually have my virtual system set up again. Just from what I can see in the commit though, everything looks pretty good!
