### ISSUE TITLE
[BUG] Typed text is invisible in kitty scratchpad until the workspace is switched.

### ISSUE THREAD

**Issue by JunaidQrysh** [hyprland-community/pyprland#128]
**Pyprland version**
2.4.0-46

**Describe the bug**
Kitty scratchpad does not show what i type until i switch a normal workspace, then the typed text becomes visible. I have tried with normal "kitty" and "kitty-dropterm".

**To Reproduce**
1.Toggle kitty scratchpad
2.Type something
3.Toggle again
4.Switch to a different workspace
5.Toggle again
6.Type something, now it should be invisible
7.Switch workspace, now the text will become visible

**Expected behavior**
Kitty should show typed text every single time

**Configuration (provide following files/samples when relevant):**
[scratchpads.kitty]
animation = ""
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"

**Additional context**

**Comment by JunaidQrysh** [comment]
I have found what is causing this bug.
Once I added (size) parameter the bug is gone.
Removing it causes it again

**Comment by fdev31** [comment]
Can you make a screenshot ?
You mean kitty shows but the window isn't updated ? Or is it really about the input ? (eg: if you run "top" in the kitty, is it updated?)

I doubt this can be fixed in Pyprland, must be an Hyprland bug, but maybe I didn't fully understand the exact problem.

**Comment by JunaidQrysh** [comment]
Sorry for the late reply.
Here is the demonstration in steps.
BeforeSizeParameter.
![1 BeforeSizeParam](https://github.com/user-attachments/assets/17e19f7e-1d51-42c6-819f-3f689beb47fa)
Typed and closed Scratchpad.
![2 TypedAndClosedScratchpad](https://github.com/user-attachments/assets/993c2b58-b37a-40c3-97bd-342bd5d61993)
Switched Workspace And Opened Scratchpad and typed.
![3 SwitchedWorkspaceAndOpenedAndTyped](https://github.com/user-attachments/assets/5128565d-8334-48e8-8faf-51385bb111da)
Switched Workspace without closing scratchpad and typed text appears.
![4 SwitchedWorkspaceAndTextAppears](https://github.com/user-attachments/assets/cc848f5f-66ef-4296-be0b-ca82fb80bbba)

The above issue is fixed after adding the size parameter in config.

**Comment by fdev31** [comment]
Two options here:

- it's a focus problem, then I may need to do something in Pyprland
- it's an input handling issue (or window refresh, can you try running "top" and see if it updates ?) : then you should open a bug for Hyprland instead

I believe providing the `size` adds some delay or changes some state in Hyprland and "fixes" the issue you found... Pyprland have no control on the input or drawing of the scratchpads, but the focus.

**Comment by fdev31** [comment]
Do you still experience it using Hyprland 0.42 ?

**Comment by JunaidQrysh** [comment]
> Do you still experience it using Hyprland 0.42 ?

yup, its still present.

**Comment by fdev31** [comment]
I don't think I can do anything with this bug, it must be reported to Hyprland... hence closing it.
