### ISSUE TITLE
[BUG] Pypr Doesnt Start : Fail to parse version information in NIXOS

### ISSUE THREAD

**Issue by aurreland** [hyprland-community/pyprland#130]
**Pyprland version**
2.3.4

**Describe the bug**
When executing pypr i get this return : 
```
Fail to parse version information: {'branch': '', 'commit': 'fabc30df52ab5d2c369fc8acd4ff909a6ba3b8ac', 'dirty': False, 'commit_message': '', 'commit_date': '2024-06-19', 'tag': '', 'commits': 'fabc30df52ab5d2c369fc8acd4ff909a6ba3b8ac', 'flags': []}
FAILED b'ok\n\n\nok\n\n\nok\n\n\nok'
^Ccancelled
```
I've seen that pypr doesnt only parse pyprland.toml for some reasons but also my kitty/colors.conf for some reasons and was throwing errors about the config file before i fixed it.
I have tried installing pyprland from the flake, from home.packages stable and unstable and by overriding with the src from github.

**Expected behavior**
Pypr Starting

**Configuration (provide following files/samples when relevant):**
- pyprland.toml
```
[pyprland]
plugins = 
  "scratchpads"
]

[scratchpads.term]
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "40% 30%"
```

it is written in a nix file using xdg.configFile."hypr/pyprland.toml" = {
enable = true;
text = ''
_the config_
'';
};

**Comment by aurreland** [comment]
Fixed it by removing my colors.conf from kitty, but there is still a problem why is it parsing .config/kitty/*

**Comment by fdev31** [comment]
This is a packaging issue, try using the `version` attribute https://hyprland-community.github.io/pyprland/Troubleshooting.html#force-hyprland-version

Can you show the log of a failed session when it parses your kitty config? It's very surprising...

**Comment by aurreland** [comment]
> hyprctl -j version
```
{
    "branch": "",
    "commit": "8ec3dc4c09c30aab7669f99ba6359be320023fa8",
    "dirty": false,
    "commit_message": "",
    "commit_date": "2024-07-30",
    "tag": "",
    "commits": "8ec3dc4c09c30aab7669f99ba6359be320023fa8",
    "flags": []
}
```
I dont have the logs of when it parsed kitty but it gave me the error that some things where not syntaxicly correct

**Comment by fdev31** [comment]
I believe the log you saw is kitty's output, since it's being launched by pyprland.

And the "tag" is missing, you are not using an "official" release or there is a packaging problem. Check the link I provided in case it causes any trouble.

**Comment by aurreland** [comment]
I think it's the log of kitty when launched. I can't test it for now on, I'm using unstable branch of nixpkgs for pyprland and the flake for hyprland. I'll test it when I can, I'll close the issue for now.
