### ISSUE TITLE
[FEAT] Toggle floating scratchpads

### ISSUE THREAD

**Issue by robertoash** [hyprland-community/pyprland#141]
Amazing features in this project! Thank you for taking the time to take feedback into consideration :)

**Is your feature request related to a problem? Please describe.**
I use the master layout in Hyprland so I don't have any floating windows. When I do `pypr toggle blueman`, the command is issued and the window popus up. However, there is no "fromTop" animation and it just comes up as a regular window within the master layout. The window can be closed issuing `hypr toggle` again.

The only animation I see when the window is opened is the one specified in the hyprland.conf.

This works overall but it serves more like an app launch toggle than a scratchpad toggle.

**Describe the solution you'd like**
I would like `pypr toggle` to create a floating scratchpad window when the layout is master or at least that there was an option in the toml to get a floating window just as there is a pinned option.

**Describe alternatives you've considered**
`floating = true` included as an option under [scratchpads.name] in the pyprland.toml

**Additional context**

**Pyprland version**
2.4.0-49

- pyprland.toml

```
[pyprland]
plugins = [
    "magnify",
    "toggle_special",
    "scratchpads"
]

[scratchpads.blueman]
animation = "fromTop"
command = "blueman-manager"
class = "blueman"
size = "30% 30%"
position = "500px 500px"
max_size = "850px 720px"
margin = 50
lazy = true
allow_special_workspaces = true
preserve_aspect = true
unfocus = "hide"
```

- hyprland.conf

My hyprland conf is very extensive but here are some of the relevant parts:

```
# Source config files
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/launch.conf
source = ~/.config/hypr/keywords.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/workspaces.conf

# Some default env vars.
env = XCURSOR_SIZE,24


# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    kb_layout = se
    kb_variant = nodeadkeys
    kb_model = pc104
    kb_options =
    kb_rules =
    follow_mouse = 1
    touchpad {
        natural_scroll = no
    }
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    numlock_by_default = true

}

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 5
    gaps_out = 20
    border_size = 2
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)
    layout = master
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 10
    blur {
        enabled = true
        size = 7
        passes = 5
        new_optimizations = true
        special = true
    }
    drop_shadow = yes
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
    dim_inactive = false
    dim_strength = 0.4
    dim_special = 0.2
}

animations {
    enabled = yes
    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section
    preserve_split = yes # you probably want this
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    new_on_top = false
    new_on_active = none
    mfact = 0.65
}

gestures {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    workspace_swipe = off
}

misc {
    mouse_move_enables_dpms = false
    key_press_enables_dpms = true
}

# Toggle Special Workspaces
bind = SUPER, B,exec, pypr toggle blueman

```

I can provide more if needed.

**Comment by fdev31** [comment]
Is it really possible?
You say there can't be any floating window, what is your idea?

**Comment by robertoash** [comment]
It should be possible. The thing with master layout is that windows are tiled and not floating by default. But they can be made to float. For example, this sets a tiled window to floating: `hyprctl dispatch togglefloating`.

So my idea is that before the `pypr toggle scratchpad_name` is issued, it checks if the layout is master (or dwindle) and floats the `scratchpad_name` if it is.

To check if the layout is master or dwindle, one option would be to examine the output of `hyprctl getoption general:layout`. In my case, the output of that command is:
```
❯ hyprctl getoption general:layout
str: master
set: true
```

**Comment by fdev31** [comment]
It makes little sense to me since on the dwindle windows are also not floating by default, the first thing pypr is doing is setting them floating.
You also mentioned setting the window as floating "manually" isn't working as expected, so maybe it's the window class or whatever you are using to set the property which is incorrect?

**Comment by robertoash** [comment]
I may not be explaining the issue properly. My master layout works without issues currently. Windows don't float by default (which is the expected behavior on master). Issuing `hyprctl dispatch togglefloating` makes the windows float without issues.

Now, when I issue `pypr toggle blueman`, the blueman scratchpad launches with no animation and as a regular tiled window. It's not floating by default.  Here's a video of it.

https://github.com/user-attachments/assets/587c89f4-897f-4e56-95c0-dbca517e3e92

I am not sure if this is expected behavior or if it's a bug in my setup.

**Comment by fdev31** [comment]
Yes, did you set the right "class" attribute for it ? I see you are using "blueman" instead of "blueman-manager" (at least on my system).
This is probably the reason for pyprland not being able to manage the floating state.

**Comment by robertoash** [comment]
That was it. Now it's floating :smile: 

I was mistaken in thinking the class attribute was what you wanted the class of the launched window to be. But I really appreciate your help!
