### ISSUE TITLE
[FEAT] Support kitty single instance for scrachpads

### ISSUE THREAD

**Issue by samtrek** [hyprland-community/pyprland#144]
**Is your feature request related to a problem? Please describe.**
using the kitty only one single instance feature, launches the first programs but the others only return errors for example

using the below as a variable
[pyprland.variables]
term_classed = "kitty -1  --class"

then below as scratpads
[scratchpads.term]
animation = "fromTop"
command = "[term_classed] term"
class = "term"
size = "30% 45%"
max_size = "1920px 100%"

[scratchpads.btop]
animation = "fromTop"
command = "[term_classed] btop -e btop"
class = "btop"
size = "45% 45%"
max_size = "1920px 100%"

[scratchpads.nchat]
animation = "fromTop"
command = "[term_classed] nchat nchat"
class = "nchat"
size = "45% 45%"
max_size = "1920px 100%"

**Describe the solution you'd like**
A single instance of kitty should be able to run with all the above without returning erros

**Describe alternatives you've considered**

**Additional context**

**Comment by fdev31** [comment]
I believe https://hyprland-community.github.io/pyprland/scratchpads_nonstandard.html#match-by is what you are looking for

**Comment by samtrek** [comment]
Yes that somehow fixed the issue.
