### ISSUE TITLE
[BUG] pyprland  plugin? fails to load.

### ISSUE THREAD

**Issue by aenairlark** [hyprland-community/pyprland#145]
**Pyprland version**
2.4.1

**Describe the bug**
Error when initializing plugin scratchpad, (AttributeError: 'dict' object has no attribute 'uid'.

**To Reproduce**
1. exec command 'pypr' in terminal.
2. returns above mentioned error.

**Expected behavior**
Start the pyprland daemon.

**Additional context**
Error initializing plugin scratchpads:
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pyprland/command.py", line 171, in __load_plugins_config
    await asyncio.wait_for(self.plugins[name].on_reload(), timeout=5.0)
  File "/usr/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pyprland/plugins/scratchpads/__init__.py", line 103, in on_reload
    scratch.uid,
    ^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'uid'
Command failed.

**Comment by CaptaiNiveau** [comment]
Yeah, I'm experiencing the same issue with the latest release

**Comment by CaptaiNiveau** [comment]
Yes, that worked, thanks!

I had a duplicate class for two terminals. That also explains the weird glitches I sometimes had - I guess living without the scratchpads for a day was worth it :D

I'm curious if there's a place where people share their scratchpad configs, I'm curious what other people were up to. I use these scratchpads for terminals daily, it's really useful. Thank you!

**Comment by aenairlark** [comment]
`[pyprland]
plugins = [
 # "expose",
 # "fetch_client_menu",
 # "lost_windows",
 # "magnify",
 "scratchpads",
 # "shift_monitors",
 # "toggle_special",
 # "workspaces_follow_focus",
]

# using variables for demonstration purposes (not needed)
[pyprland.variables]
term_classed = "alacritty --class"

[scratchpads.term]
animation = "fromTop"
command = "[term_classed] main-dropterm"
class = "main-dropterm"
size = "70% 60%"
max_size = "1920px 100%"
unfocus = "hide"

[scratchpads.volume]
animation = "fromBottom"
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
lazy = true
size = "40% 60%"
unfocus = "hide"

[scratchpads.bluetuith]
animation = "fromBottom"
command = "[term_classed] bluetuith -e bluetuith"
class = "bluetuith"
lazy = true
size = "40% 50%"
unfocus = "hide"

[scratchpads.iwgtk]
animation = "fromBottom"
command = "iwgtk"
class = "org.twosheds.iwgtk"
lazy = true
size = "40% 50%"
unfocus = "hide"

[scratchpads.clock]
animation = ""
command = "kitty --class tty-clock -e tty-clock -D -c -b -C 4"
class = "tty-clock" #alacritty dosent like tty-clock for some reason using pypr
lazy = true
size = "18% 16%"
unfocus = "hide"

[scratchpads.btop]
animation = ""
command = "[term_classed] btop -e btop"
class = "btop"
lazy = true
size = "45% 50%"
unfocus = "hide"
`

i fixed some class errors given by pypr. This is how i did my config.
