### ISSUE TITLE
[BUG] Fail to start pyprland-2.4.1

### ISSUE THREAD

**Issue by piyoki** [hyprland-community/pyprland#146]
**Pyprland version**
Which version did you use? (copy & paste the string returned by `pypr version`)

2.4.1

**Describe the bug**

On NixOS; install pyprland with flake

```console
⯁ flake git:(master) ❯❯❯ pypr
Error loading plugin pyprland:
Traceback (most recent call last):
  File "/nix/store/f7dmgvmi8y0085pj5rmlv31n3fv4n2qs-python3.11-pyprland-2.4.1/lib/python3.11/site-packages/pyprland/command.py", line 141, in _load_single_plugin
    await plug.init()
  File "/nix/store/f7dmgvmi8y0085pj5rmlv31n3fv4n2qs-python3.11-pyprland-2.4.1/lib/python3.11/site-packages/pyprland/plugins/pyprland.py", line 37, in init
    version_str = version_info["version"]
                  ~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'version'
Command failed.
⯁ flake git:(master) ❯❯❯
```

**To Reproduce**

**Expected behavior**

**Configuration (provide following files/samples when relevant):**
- pyprland.toml
- hyprland.conf

**Additional context**

**Comment by fdev31** [comment]
Can you provide the output of `hyprctl -j version` ?

**Comment by fdev31** [comment]
Your hyprland build is unsupported, it should have a version and/or a tag, yours have nothing.
There was a fallback, assuming "latest version" when nothing is available, I guess this broke, I'll keep this bug open for this fix.

**Comment by fdev31** [comment]
The git version should contain the fix

**Comment by piyoki** [comment]
> The git version should contain the fix

Cool, let me have a try. Thanks for the kind support!

**Comment by piyoki** [comment]
> > The git version should contain the fix
> 
> Cool, let me have a try. Thanks for the kind support!

It is now working like a charm!

```nix
# flake.nix
input = {
    pyprland = { url = "git+https://github.com/hyprland-community/pyprland?tag=2.4.2"; };
}
```
