### ISSUE TITLE
[BUG] Fails to build on NixOS Unstable

### ISSUE THREAD

**Issue by Averyfrog** [hyprland-community/pyprland#147]
**Pyprland version**
2.4.0

**Describe the bug**
the version of aiofiles is outside of the version range for the dependency

**To Reproduce**
attempt to rebuild NixOS
```
       > Checking runtime dependencies for pyprland-2.4.0-py3-none-any.whl
       >   - aiofiles<24.0.0,>=23.2.1 not satisfied by version 24.1.0
```
**Expected behavior**
It builds

**Comment by fdev31** [comment]
I'll publish a version with more relaxed dependencies versions

**Comment by clotodex** [comment]
Still failing for me

**Comment by fdev31** [comment]
Is the message the same?
Do you have a chance to make local changes to understand what's locking the
version resolution?

**Comment by clotodex** [comment]
the email did likely not transmit my edit
the issue is fixed - it was my mistake, used the unstable verison, not master. Master is building now as flake input :)

**Comment by Averyfrog** [comment]
great, thanks for fixing the issue! I'll close it
