### ISSUE TITLE
Question on match_by

### ISSUE THREAD

**Issue by samtrek** [hyprland-community/pyprland#150]
According to the documentation, scratchpads can be identified according to pid, class, tittle, when class and not pid is selected as below

match_by="class"

Are there `process_tracking`  tracked by their pid or their class, or the match_by is only to determine position, decoration e.t.c... and not used in process tracking?

**Comment by samtrek** [comment]
1. Yes I was wondering that if `process_tracking = true` and the `match_by = class`, can we not start terminal apps that share same PID but have  different class set by their scratchpad configs. The solution you proffered in #144 did not work as envisaged, totally disabling `process_tracking` is the only thing that worked.
2. I was wondering that can we not force `lazy=true` when `process_tracking = false`, I tried to force it on for an app that I want to start at start upbut it did not work.

**Comment by fdev31** [comment]
1. if you enable process tracking, there will be some conflicts indeed. It assumes the window has been launched by the process specified under "command".
2. Not sure what you try to achieve, but when process_tracking is False, it's ALWAYS using lazy mode (which is the default anyway).

**Comment by samtrek** [comment]
pardon me, what I want to achieve is set some apps to auto launch at login even  if `process_tracking=false`, however setting to `lazy=false` did not achieve the desired result.

**Comment by fdev31** [comment]
yes, because lazy is FORCED when you have no process tracking to avoid some issues. I can tell you how to disable this behavior if you like to experiment.

**Comment by samtrek** [comment]
> yes, because lazy is FORCED when you have no process tracking to avoid some issues. I can tell you how to disable this behavior if you like to experiment.

I can give it a try if it causes more issues than the benefits it will provide, then I can continue to use the method I am using which is  `exec-once = sleep 5 && pypr show btop && pypr hide btop`    in hyprland config, the sleep is to ensure pypr is fully initialized.

**Comment by fdev31** [comment]
You can just remove one line of code in pyprland/plugins/scratchpads/objects.py around line 98:

```diff
diff --git a/pyprland/plugins/scratchpads/objects.py b/pyprland/plugins/scratchpads/objects.py
index 9b3fc53..9eff5dd 100644
--- a/pyprland/plugins/scratchpads/objects.py
+++ b/pyprland/plugins/scratchpads/objects.py
@@ -95,7 +95,6 @@ class Scratch(CastBoolMixin):  # {{{
         if not self.have_command:
             opts["match_by"] = "class"
         if not opts.get("process_tracking", True):
-            opts["lazy"] = True
             if "match_by" not in opts:
                 opts["match_by"] = "class"
         if state.hyprland_version < VersionInfo(0, 39, 0):
```

You'll need to restart pyprland daemon for this change to have any effect.

**Comment by fdev31** [comment]
Any update ?

**Comment by samtrek** [comment]
Yes let us close the issue, I could not find a way of carrying out the modification you suggested and new hyprland versions did not fix the issue.
