### ISSUE TITLE
[BUG] IPC socket file is not removed on SIGTERM

### ISSUE THREAD

**Issue by AThePeanut4** [hyprland-community/pyprland#151]
**Pyprland version**
2.4.3-5

**Describe the bug**
The `.pyprland.sock` IPC socket file isn't removed when `pypr` is terminated with a SIGTERM. This causes subsequent `pypr` commands to fail with "Trying to run pypr more than once?".

**To Reproduce**
1. Run `pypr`
2. Observe that `$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.pyprland.sock` exists
3. Run `killall -TERM pypr`
4. Observe that `$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.pyprland.sock` still exists
5. Run `pypr`
6. Observe "Trying to run pypr more than once?" error message.

**Expected behavior**
The IPC socket should be removed, like what happens when the process receives a SIGINT.

**Additional context**
Context is that I'm setting up [uwsm](https://github.com/Vladimir-csp/uwsm) to run my Hyprland session using systemd, and as part of that I'm trying to move background services, such as pyprland, to systemd units. By default, systemd kills units using a SIGTERM, which is how I encountered this issue. The workaround is to tell systemd to use a SIGINT using `KillSignal=SIGINT`, but imo this shouldn't be necessary - the socket should be removed on both SIGINT and SIGTERM.

**Comment by fdev31** [comment]
There is a `pypr exit` command to terminate it.
