### ISSUE TITLE
[BUG] Scratchpads with different positions on monitors sometimes position wrong

### ISSUE THREAD

**Issue by alexjp** [hyprland-community/pyprland#153]
**Pyprland version**
2.4.3

**Describe the bug**
I am using hyprland with pyprland and have a two monitors. I setup a configuration like for example:
```
[scratchpads.notes]
animation = "fromBottom"
#lazy = true
size = "1920px 1400px"
#unfocus = "hide"
#hysteresis = 1
hide_delay = 0.1

[scratchpads.notes.monitor.DP-2]
position = "32px 20px"
[scratchpads.notes.monitor.DP-1]
position = "608px 20px"
```

I also have in hyprland:
```
  follow_mouse = 2
```

which means that focus does not strictly follows mouse.

So what happens is if I have the focus on left-monitor and the mouse on the right-monitor, the window will appear on the right-monitor on the first time, but if I toggle it a second time, it will appear on the left-monitor but in the position settings of the right-monitor.

**To Reproduce**
1. Configure pyprland like in the above (different positions per monitor)
2. Focus with the keyboard a window on one monitor
3. Move mouse to the other monitor
4. Toggle a scratchpad one time, window in mouse and correct placement. Toggle it another time without moving the mouse, it will appear on the wrong monitor/position.

**Expected behavior**
Either to show on the monitor of the focused window in the correct place, or in the monitor of the mouse in the correct place.

**Configuration (provide following files/samples when relevant):**
See above

**Additional context**
I am kinda new to hyprland, so if any missing info, feel free to request it. If it is a mistake on my part, sorry for taking your time!

Thanks!

**Comment by fdev31** [comment]
Can you try disabling `smart_focus` ?

**Comment by alexjp** [comment]
> Can you try disabling `smart_focus` ?

That seems to do it!! :) Thanks!

Sorry, the solution was in the documentation. Thank you for your time!
