### ISSUE TITLE
[BUG] Scratchpad cannot be toggled to full screen directly

### ISSUE THREAD

**Issue by Ram-256bit** [hyprland-community/pyprland#156]
**Pyprland version**
2.4.1

**Describe the bug**
When using scratchpads, I cannot make them full screen directly using the full-screen shortcut.

**To Reproduce**
1. Open a scratchpad.
2. Focus on the scratchpad.
3. Press the full-screen shortcut.

**Expected behavior**
When a scratchpad is opened and in focus, pressing the full-screen shortcut should:
1. Make the scratchpad full screen.
2. Return it to its normal floating state and position when the full-screen shortcut is pressed again.

**Actual behavior**
Pressing the full-screen shortcut while a scratchpad is opened and in focus does nothing.

**Workaround (That I'm using now)**
1. Open the scratchpad and ensure it is in focus.
2. Use the shortcut to toggle the floating state off.
3. Press the full-screen shortcut.
This allows the scratchpad to go full screen.

**Comment by fdev31** [comment]
Try setting `pinned = false`

**Comment by Ram-256bit** [comment]
It works! Thanks for the solution!

**Comment by Sneethe** [comment]
If you still want pinned scratchpads you can can `allow_pin_fullscreen = 1`
see https://wiki.hyprland.org/Configuring/Variables/#binds
