### ISSUE TITLE
Terminal scratchpad not moving with windowrules

### ISSUE THREAD

**Issue by biscuitrescue** [hyprland-community/pyprland#2]
i was setting up a scratchpad for alacritty. i did as specified in the wiki, and gave it a class name. its floating, but its position such that the right edge of the terminal touches to end of the screen, and i cant move it around with windowrule=move. any help?

**Comment by fdev31** [comment]
Do you mean the windowrule isn't doing anything ?
Are you making this window floating ?
And then toggling the scratchpad doesn't move the window either ?
 Can you copy the relevant configuration files here ?

**Comment by fdev31** [comment]
Hm... this looks more like an issue with hyprland then. Which version are you running ? You may try to report it to the hyprland team. If the hyprland rules aren't working I doubt the rest will work...

**Comment by biscuitrescue** [comment]
but windowrule=move is working for every other application ive set it for? Ive set up spotify, dolphin and nautilus too

**Comment by fdev31** [comment]
No feedback = no problem (re-open if you are still interested & made progress). If you opened a bug in hyprland and it's fixed, you are welcome to update the ticket too!
