### ISSUE TITLE
[Feature Request] Add an option to display at most one scratchpad at a time

### ISSUE THREAD

**Issue by cunbidun** [hyprland-community/pyprland#21]
Hey! Thanks for the awesome plugins. 

I've got a small feature request. It'd be really helpful if we could add an option to automatically hide visible scratchpads when toggling or creating a different one.

**Comment by fdev31** [comment]
Hi!
If you add:
```
       "unfocus": "hide"
```
On each of your scratchpads, do you achieve that or it's not really perfect ?

**Comment by cunbidun** [comment]
Hey, thanks for the quick response. 

The "unfocus": "hide" feature works perfectly as intended. However, sometimes, I don’t want the scratchpad to disappear when losing focus. For example, when I need to copy and paste commands from a browser to the terminal scratchpad.

**Comment by fdev31** [comment]
It would be easy to have it as a global option for every scratchpad: `"exclusive_focus": true`, for instance.

Another way could which seems more flexible would be to have a per-scratch attribute telling a list of scratches which should be hidden if this one is shown: `"excludes": ["scratchpadX", "otherPad"]`

I may prefer the later.
Do you have other ideas or comments about this ? Or suggestions about the naming...

**Comment by cunbidun** [comment]
Both are good options. I’d prefer the first option. The second sure gives more flexibility, but also adds more implementation complexity

**Comment by fdev31** [comment]
Check https://github.com/hyprland-community/pyprland/wiki/Plugins#excludes-optional & latest git version if you can

**Comment by fdev31** [comment]
To me it's allowing to do what to expect, I added a shortcut syntax to make it more convenient to configure.
Re-open if I misunderstood or if you get troubles using it.
