### ISSUE TITLE
Build broken on nixpkgs-unstable due to removal of poetry2nix

### ISSUE THREAD

**Issue by dantefromhell** [hyprland-community/pyprland#25]
The removal of poetry2nix happened tree-wide in https://github.com/NixOS/nixpkgs/pull/263308, the recommended fix is to add a current upstream to `flake.nix` of pyprland.

The weblate project seem to have had the same problem, their implementation can be found in https://github.com/ngi-nix/weblate/blob/main/flake.nix

I'll be willing to try myself on a PR if helpful.

**Comment by dantefromhell** [comment]
It's possible to workaround this issue by pinning `nixpkgs-unstable` to the commit before the `poetry2nix` removal by source `pyprland` like this: 

```nix
inputs.pyprland = {                                                                                                        
  url = "github:hyprland-community/pyprland/";                                                              
  inputs.flake-utils.follows = "flake-utils";                                                                       
};                                                                                                                  
inputs.pyprland-nixpkgs-unstable.url = "github:NixOS/nixpkgs/fa9ab56301568aa470563d7b60e2ab7fc886546a";                    
inputs.pyprland.inputs.nixpkgs.follows = "pyprland-nixpkgs-unstable";          
```

**Comment by fdev31** [comment]
So I'm really not the nix package maintainer, it was contributed... I don't have nix...
I'm not sure what to do exactly... would you be able to make a pull request to fix this ?

**Comment by fdev31** [comment]
Since there are no python lib dependencies in this project, there is a way to build the package without poetry, using https://pypi.org/project/build/ - then you can install the generated .wheel file using pip or even just copying the folder in the right place...
But I'm afraid you'll have to create the "pypr" command in the nix file, it should be running "python -m pyprland.command"

More nix people can contribute eventually, since I don't really know what I'm talking about... I can just help on the Python part... @iliayar @yavko maybe ?

**Comment by iliayar** [comment]
@dantefromhell Hello. pyprland is on nixpkgs https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/py/pyprland/package.nix#L34. But it's not the last version yet, and having flake is good anyway. You can use derivation from there in flake. The version on nixpkgs doesn't use `poetry2nix`.

**Comment by fdev31** [comment]
Should I remove the .nix file from the repository ?

**Comment by iliayar** [comment]
Sure, assign me. Will make fix soon. `flake.nix` will allow to use newer version than one on nixpkgs.
