### ISSUE TITLE
opening firefox - open a normal hyprland window

### ISSUE THREAD

**Issue by realsnick** [hyprland-community/pyprland#35]
tried this configuration:
```ini
[scratchpads.nixpkgs-search]
animation = "fromTop"
command = "firefox --no-remote --class nixpkgs-search --new-window https://search.nixos.org/packages"
class = "nixpkgs-search"
lazy = true
size = "50% 75%"
position = "25% 5%"
excludes = "*"
```
get this error:
`Failed spawning nixpkgs-search as proc 608846
"firefox --new-window https://search.nixos.org/packages": The command terminated sucessfully, is it already running?
Failed to show nixpkgs-search, aborting.`

PS. also tried without the class

![image](https://github.com/hyprland-community/pyprland/assets/1440852/ee6e236b-51f7-47fd-bc9f-a780854e569e)

**Comment by fdev31** [comment]
Sorry, I'm not getting the issue.
I see in the screenshot the window is appearing. Do you mean as soon as you use "class" this will not work anymore and you get the error you provided ?

**Comment by realsnick** [comment]
doesn't the window should appear floating?

**Comment by realsnick** [comment]
Thanks! though i thought without the class it should go with the `pid` but that didn't work either so got confused on the usage. Any browser recommendations that will work? i'll try to dig to the class of firefox and reply if i find it.

**Comment by fdev31** [comment]
Don't have much experience using webapps as scratchpads but you may be interested in #31 . On google I found some bugs for chrome regarding "class" handling, I can imagine there are similar issues with firefox.
If you get it to work feel free to share, I'll add it to some example in the wiki.

**Comment by realsnick** [comment]
thank you @CaptaiNiveau i'll give it a try later this week
