### ISSUE TITLE
[Feature Request] Move the scratchpad to new workspace instead of closing it

### ISSUE THREAD

**Issue by cunbidun** [hyprland-community/pyprland#36]
Hi, I'm using the scratchpad plugin with the `unfocus` set to `""` (no action), so that it won't automatically close when losing focus. I'm having the following minor inconvenience.

Step to reproduce:
1. Toggle the scratchpad on Workspace 1
2. Switch to Workspace 2 
3. Toggling the scratchpad again

Currently, pypr will close the scratchpad because it remains open in workspace 1. I think it would be more intuitive if the scratchpad moves from workspace 1 to workspace 2.

**Comment by fdev31** [comment]
Hi,
which version have you been using ?
I think this was implemented in https://github.com/hyprland-community/pyprland/tree/1.6.5

**Comment by cunbidun** [comment]
I was on 1.6.1. Confirmed that 1.6.8 addressed this issue. Closing.

**Comment by cunbidun** [comment]
Hi @fdev31, I'm on 2.0.5 and this feature seems not working. Please take a look when you have a chance. Thank you so much!

**Comment by dantefromhell** [comment]
Any chance this could become a configuration flag? 

I personally prefer the behaviour of being able to close a scratchpad when my focus is on a different screen/ monitor.

**Comment by fdev31** [comment]
Is it ALWAYS when the scratchpad is visible (eg: multi-screen setup).
I can hide when visible & move if the workspace isn't visible eventually...

**Comment by dantefromhell** [comment]
> Is it ALWAYS when the scratchpad is visible

Yes always.

Whenever I switch monitors or workspaces while my kitty scratchpad is open, executing `pypr toggle $NAME` brings the scratchpad to the current focused workspace/ monitor first, executing `pypr toggle $NAME` again will hide it.

**Comment by dantefromhell** [comment]
@fdev31 Any updates on this?
I'm still experiencing this behaviour with `2.2.3`. Should I open a separate issue/ bug?

**Comment by fdev31** [comment]
> @fdev31 Any updates on this?
> I'm still experiencing this behaviour with `2.2.3`. Should I open a separate issue/ bug?

Oh indeed I forgot. Maybe a feature request... But instead of one more obscure option, maybe I can implement the behavior I described which may fit everybody... What do you think about it?

**Comment by dantefromhell** [comment]
I assume you are referring to

> I can hide when visible & move if the workspace isn't visible eventually...

That sounds like a good enough compromise to me. My personally irritation is that my kitty scratchpad is moved to the visible:focused monitor+workspce instead of being closed on visible+unfocused monitor.

**Comment by fdev31** [comment]
> I assume you are referring to
> 
> > I can hide when visible & move if the workspace isn't visible eventually...
> 
> That sounds like a good enough compromise to me. My personally irritation is that my kitty scratchpad is moved to the visible:focused monitor+workspce instead of being closed on visible+unfocused monitor.

Ok, I'll prepare something you can test soon... by the way, are you reachable on some public chat, Discord maybe? It could be convenient to connect once for some of your issues.
