### ISSUE TITLE
Exclude appears not working on 1.6.8

### ISSUE THREAD

**Issue by cunbidun** [hyprland-community/pyprland#37]
Hi, I just update to the latest version 1.6.8 and the exclude feature appears not working. Steps to reproduce
1. Open `term` scratchpad
2. Open  `messenger` scratchpad
3. I expect the `term` scratchpad is hidden by `pypr`, but it's not. Both scratchpad are showed at the same time.

My configurations:

```
[pyprland]
plugins = [
  "scratchpads",
]

[scratchpads.term]
command = "alacritty -t __scratchpad"
animation = ""
lazy = true
unfocus = ""
size = "50% 50%"
position = "25% 25%"
excludes = "*"

[scratchpads.messenger]
command = "caprine"
animation = ""
unfocus = ""
lazy = true
size = "50% 50%"
position = "25% 25%"
excludes = "*"
```

Thank you!

**Comment by fdev31** [comment]
Released 1.6.9 fixing the regression, thank you for the report!
