### ISSUE TITLE
how do I set up expose plugin?

### ISSUE THREAD

**Issue by Ultrahalf** [hyprland-community/pyprland#4]
```
{
  "pyprland": {
    "plugins": [
      "scratchpads",
      "expose"
    ]
  },
  "scratchpads": {
    "term": {
      "command": "wezterm start --class wezterm-dropterm",
      "animation": "fromTop",
      "unfocus": "hide"
    }
  },
  "expose": {
    "include_special": true
  }
}
```

```
Error loading plugin expose: No module named 'pyprland.plugins.expose'
```

also it would be nice to have `pypr --version`

**Comment by fdev31** [comment]
I take note for the `--version`, I was about to ask you which version you use :)
Check if you have an "expose.py" file in the package...
My guess: you are using the last release (1.3.1) or older, while expose is only available in the git version... you may just copy the file from git and it should work (but it's a hack).
