### ISSUE TITLE
Scratchpads running, but wont show up

### ISSUE THREAD

**Issue by darkshitllord** [hyprland-community/pyprland#40]
I'm experiencing a problem where when i run an application in a scratchpad it does run the program but wont display it. I think this problem occurs when a program is running trough xwayland instead of native wayland, since everything I've tried so far suggests that being the issue. It would be nice if someone could try reproducing it because I've not seen anyone online raise this issue. I'm running arch linux if that information helps.

Maybe this isn't even a pyprland problem but a hyprland one, not sure.

**Comment by fdev31** [comment]
what happens if you launch the app from a terminal instead ?

**Comment by darkshitllord** [comment]
this is the configuration i generally have for a few windows:

`$code = class:^(code-oss)$
windowrulev2 = float, $code
windowrulev2 = $scratchpadsize, $code
windowrulev2 = workspace special silent, $code
windowrulev2 = center, $code`

this one:

`windowrulev2 = workspace special silent, $code`

makes the window not appear when trying to toggle it, but I've only encountered this problem with programs running trough xwayland.

So when i launch the application without this window rule it seems to work as intended, but if not it won't appear.

**Comment by fdev31** [comment]
Oh ok, if you added some special configuration like this it's probably the problem since it's not using the same as the internal settings.

Pypr will set the workspace and floating state for you, no need for a configuration if you set the `class` attribute.

**Comment by darkshitllord** [comment]
Unfortunately that does not fix the problem, for example vs code does not even appear when the class attribute is set, qbittorrent and vlc appear but lose functionality, after some certain actions (when removing a torrent in qbittorrent, or when pressing any button in vlc) they freeze and cannot be interacted with. When i remove the class attributes they work as intended. I have no clue as to what could be causing the issues.

**Comment by fdev31** [comment]
Not all apps get the same parameters.
Without any parameter, vscode have the class "Code" here.
Can you check on your environment and see if setting class="Code" or whatever you see on your system fixes the problem ?

I'm also wondering what kind of problem you experience on your system, it's not really something that can be produced by Pyprland.

**Comment by darkshitllord** [comment]
Unfortunately I've had no luck with fixing this problem. I usually check for classes by doing `hyprctl clients`, it also displays which programs are running trough xwayland, that's why i thought maybe that was the issue since all of the programs causing issues do.

Since the specific class for vscode is "code-oss", at least on my system ,setting anything other than that just executes the command and displays another instance of vscode. And if the class "code-oss" is set it just creates a new instance every time but places it in a special workspace, making me unable to actually display the program.

Currently i have no clue as to what could be causing the problem.

**Comment by fdev31** [comment]
I just tested vscode, it's indeed broken because the process exits and behaves like a progressive web app.
Check https://github.com/hyprland-community/pyprland/wiki/Troubleshooting#disable-process-management

I had success with the following configuration (you will probably need to adapt command & class to match your system):

```toml
[scratchpads.code]
animation = "fromLeft"
command = "code"
lazy = true
class = "Code"
process_tracking = false
size = "40% 45%"
position = "5% 5%"
```

**Comment by fdev31** [comment]
In short, you must use "class" and try combinations of `process_tracking=false` and `class_match=true`.

Is it working for you ?

**Comment by fdev31** [comment]
Did you also enable class matching ?
This is absolutely needed for such apps.
By default pyprland tracks the created window using the process ID, but some apps don't work in a "straightforward" way, making this unreliable.

**Comment by fdev31** [comment]
Glad it's finally working :)
I may highlight those "workarounds" more, I've seen few people struggling with similar items online...
