### ISSUE TITLE
[Feature Request] Minimization Plugin Integration with Scratchpads

### ISSUE THREAD

**Issue by cunbidun** [hyprland-community/pyprland#42]
Hi,

Thank you for the fantastic project. I'd like to propose the addition of minimization features through a new plugin. Here are some of the functionalities I'm suggesting:

1. Introduce a dock/secondary bar, similar to [nwg-dock-hyprland](https://github.com/nwg-piotr/nwg-dock-hyprland) or the awesomewm bar:
   - Enabling users to click on a window icon to toggle the visibility of the corresponding window.

2. Provide an option to display only windows in the current workspace.

3. Ensure compatibility with the scratchpad plugin:
   - If the scratchpad is visible, the application's icon should be present in the dock.
   - If the scratchpad is not visible, the application's icon should be removed from the dock.

I understand this is a lot to ask for, so please let me know if you think it worth implementing.

Thank you.

**Comment by cunbidun** [comment]
Actually, to make things less complicated, we probably don't need a GUI interface. Just need to provide some CLI command to:
1. list
2. show
3. hide

**Comment by fdev31** [comment]
Hello and thank you, show/hide is covered by `toggle_minimized` somehow ? Then a "list" feature would be enough ?

**Comment by cunbidun** [comment]
Hey, actually the `expose` plugin works pretty well for my use case. Closing
