### ISSUE TITLE
`pypr reload` doesn't seem to do anything for scratchpads

### ISSUE THREAD

**Issue by cvincent** [hyprland-community/pyprland#43]
Per the title. Updating my scratchpads cleanly requires manually closing each one, then `pkill pypr; pypr & disown`. It would be nice if `pypr reload` did this for me.

**Comment by fdev31** [comment]
Pypr reload is "just" supposed to reload the configuration by updating the in-memory structure, keeping apps open and eventually starting a new ones. A quick test seem to show it's broken at the moment, I'll have a look, thank you for the report!
