### ISSUE TITLE
scratchpads gets hidden behind in fullscreen mode

### ISSUE THREAD

**Issue by logexp1** [hyprland-community/pyprland#45]
Hi, I am gratefully using scratchpads, but there's one caveat. When I toggle scratchpad on in fullscreen mode, it gets hidden behind the current window. It does show up when I turn off fullscreen mode but I want  scratchpad to be visible whenever I toggle on whether I am in fullscreen mode or not. This does not happen initially right after booting, but happens after I open and close new windows. I feel like this could be Hyprland issue as I post this issue. If it is, please understand since I am a wayland newbie..

Thanks!

**Comment by logexp1** [comment]
I found that this does not always happen, I close this issue since it is likely from the instability of hyprland.

**Comment by fdev31** [comment]
Can you tell me which version you have been using ?

In 1.8 I fix this problem, but it requires Hyprland >= 0.30.

Before that the Z order wasn't forced, so it could be a bit random.
Please tell me you are using a version < 1.8 ;)

**Comment by logexp1** [comment]
Oh, I am using version 1.7.1. That was it, then! Thanks!
