### ISSUE TITLE
[BUG] Nix Flake build failed: "No module name 'hatchling' for pygments"

### ISSUE THREAD

**Issue by fedoranvar** [hyprland-community/pyprland#48]
**Pyprland version**
Which version did you use?
commit cb4de47d2c91828ccce6d423f6c25ce8f6427f3a

**Describe the bug**

On NixOS, flake installation fails on building

**To Reproduce**
1. Build package from flake
2. get an error

**Expected behavior**
installation without error

**Additional context**
![image](https://github.com/hyprland-community/pyprland/assets/52028706/f4b88a10-e64d-438e-8763-4e1c70e8e659)

**Comment by fdev31** [comment]
It is not a pyprland problem, rather a packaging issue in nix.
Do you have a way to report issues related to nix packages?

**Comment by NotAShelf** [comment]
should be resolved by #49

**Comment by fdev31** [comment]
@fedoranvar this seems to have been fixed, if you still have some issues building on Nix, reopen this ticket please.
