### ISSUE TITLE
[feature] Option to have a given scratchpad to only start the commands on first display

### ISSUE THREAD

**Issue by ArtemSmaznov** [hyprland-community/pyprland#5]
Loving the scratchpad functionality that this brings to Hyprland.

I am defining quite a few scratchpads, many of which I use rarely, so having them all launch on startup even though they are hidden is not ideal, at least not for the less often used ones.

Is it possible to have an option to not launch some or all scratchpads on pyprland start? I would be happy even if I have to trigger the keybinding twice to open it as currently happens if you close the scratchpad window and try to launch it again

**Comment by fdev31** [comment]
I may do some "lazy_start" option, that you can set to True, would that do ?
As far as I can imagine you will not need special hyprland rule for this window, or maybe the floating attribute if it's not one already. Then first time it will show with "default rules" (that you may override of course, using hyprland) - pypr will not apply anything, it will only start to control it when you run the command again.
What do you think about it ?

**Comment by fdev31** [comment]
Can you try the git version ? I added some option called "lazy" that you can set to true.

**Comment by ArtemSmaznov** [comment]
Hi @fdev31,

Thanks for your time. I didn't fully understand your previous message but a lazy option is what I was looking for.

I am currently away till the end of July so will check this once I am back.

**Comment by ArtemSmaznov** [comment]
@fdev31 I can't seem to be able to figure out how to install the git version - only have the regular one in the AUR. I can wait till this is released. From the description it looks exactly what I wanted though so thanks
