### ISSUE TITLE
Pyprland makes all chromium instances started with --app switch floating

### ISSUE THREAD

**Issue by Haerteleric** [hyprland-community/pyprland#52]
**Pyprland version**
2.0.4

**Describe the bug**
I use chromium instances with the --app switch for a lot of my daily apps (like discord,element,teams,spotifiy,...).

eg.:
```
[scratchpads.spotify]
animation = "fromRight"
command = "chromium --class=Spotify --user-data-dir=$HOME/.cache/chromium/spotify-webApp --app=https://open.spotify.com/"
class = "Spotify"
size = "50% 80%"
lazy = true
unfocus = "hide"
```

These work flawlessly. But i also use chromium webApp instances for stuff like outlook where i don't want them in a scratchpad. But if i exec any other chromium with the --app switch set the spawning Window starts in a floating state.

**To Reproduce**
1. Add a Scratchpad as shown in above example
2. Open a different chromium instance via shell, hotkey or launcher with --app switch active 
eg.:
```
$ chromium --class=Discord --user-data-dir=$HOME/.cache/chromium/discord-webApp --app=https://discord.com/app
```
3. New window starts in floating state.

**Expected behavior**
New window with different class Name should not start in a floating state

**Comment by fdev31** [comment]
Hi, I think it's unrelated to the "--app" switch, it's related to the classes.
Once you have a scratchpad "well configured" providing the `class` property, every matching window will be affected. Here you should remove or change your `--class` command-line option.

**Comment by fdev31** [comment]
Please reopen if my comments didn't help and you find a problem in pyprland.
Thank you for the report, I may better document the "chrome apps" in the future.
Feel free to make a proposition :)
