### ISSUE TITLE
[FEAT] Please do not send a message about the no position or no animation

### ISSUE THREAD

**Issue by gitttyyy** [hyprland-community/pyprland#59]
![图片](https://github.com/hyprland-community/pyprland/assets/154318356/0d5b0e15-6b38-410e-b897-a433c3a04590)
I do not want to use the position attributes because it can`t adapt the multi monitors,I just use hyprland rule to make a scratchpad at the center

**Comment by fdev31** [comment]
Having position: "5% 5%" and size: "90% 90%" (for instance) can do the job as well and is supported... anyway, if this is working on multi-screens I'll remove the warning.

**Comment by fdev31** [comment]
I did some tests and it's okayish with multi-screens...

**Comment by gitttyyy** [comment]
Thank you, the same need for #56 and look forward to packaging it into aur

**Comment by fdev31** [comment]
Then it's already available/ released :)
