### ISSUE TITLE
[BUG] animation = "" produces buggy behaviour

### ISSUE THREAD

**Issue by yatinlala** [hyprland-community/pyprland#61]
**Pyprland version**
pyprland 2.0.8, installed via pipx

**Describe the bug**
Scratchpads work properly with animations enabled. When animations are disabled, the window doesn't float and disrupts the workspace layout.

**To Reproduce**
1. create a scratchpad with the following settings:
`[scratchpads.notes]
command = "emacs --name notes ~/documents/org/main.org"
class = "notes"
animation = ""
margin = 50
size = "90% 90%"
max_size = "1920px 100%"
lazy = true`
2. run `pypr toggle notes`

**Expected behavior**
`animation=""` should produce a toggleable floating window. 
**Configuration (provide following files/samples when relevant):**
- pyprland.toml
`[scratchpads.notes]
command = "emacs --name notes ~/documents/org/main.org"
class = "notes"
animation = ""
margin = 50
size = "90% 90%"
max_size = "1920px 100%"
lazy = true`

- hyprland.conf
`bind = $mod,w,exec,pypr toggle notes`

**Additional context**
![ezgif-6-f0b154ae1d](https://github.com/hyprland-community/pyprland/assets/43100192/c34947c7-8ed7-4e62-9670-c10be2cdbd82)

**Comment by fdev31** [comment]
I agree, note you can easily set it floating in the hyprland config, but I'll fix that so it's aligned with other scratchpad configs.
