### ISSUE TITLE
[FEAT] Implement 'pypr version' command

### ISSUE THREAD

**Issue by dantefromhell** [hyprland-community/pyprland#62]
>Is your feature request related to a problem? Please describe.

When filing bug request the `pyprland` version number is asked. 

> Describe the solution you'd like

It would be super helpful if `pypr version` exists that outputs all relevant version and/ or library info that are requested for bug reports.

> Describe alternatives you've considered

n/a

**Comment by fdev31** [comment]
Should be working starting from version 2.0.8-12-g684d0cf ;)
