### ISSUE TITLE
[FEAT] option to disable coloring of --debug

### ISSUE THREAD

**Issue by dantefromhell** [hyprland-community/pyprland#63]
> **Pyprland version**
> Which version did you use?

python3.11-pyprland-2.0.8/

> **Describe the bug**

When running `pypr --debug /tmp/pypr.log` sections of the each logline are invisible when displayed in `less`, `cat` and `tail` (these ones I tested) using `kitty` (custom config) and `alacritty` (default config) as terminal emulator.

![image](https://github.com/hyprland-community/pyprland/assets/90508808/80a529b5-0196-4745-bffd-dc45501aee52)

The text is not missing from the logfile and becomes visible when marking the lines
![image](https://github.com/hyprland-community/pyprland/assets/90508808/5ddcab77-ebc7-4b33-afb5-84def3d75cb6)

> **Expected behavior**

All lines in the log are visible all the time, irregardless of terminal emulator used.

> **Additional context**

IMO this is ideally achieved by logging plain text that contains no ANSI control characters.

**Comment by fdev31** [comment]
Looks like you have some bug in your terminal theme ? grey shouldn't be black or at least not the same as the background color...
I can use another color but the goal was to make it not very visible because those logs are usually not very important....
I can revert to the old versions with no color but colors are quite useful to read faster IMO...

**Comment by dantefromhell** [comment]
> I can revert to the old versions with no color but colors are quite useful to read faster IMO...

Since our preferences are different, what about a CLI option to disable coloring in logs?

**Comment by fdev31** [comment]
In this case, I don't think it's preferences, in your case this is not visible at all, which is a color scheme issue in my opinion that could affect other applications.
The escape sequences are very easily stripped out with a sed expression for instance, allowing to work around your problem.
Lastly, those logs are just informative about the events emitted by Hyprland, so they are less important.
I'll keep it open but this is quite low priority on my list given the context...
