### ISSUE TITLE
pypr throws error

### ISSUE THREAD

**Issue by KSaiAkshit** [hyprland-community/pyprland#7]
I wanted to setup some scratchpads, and i followed the guide on their [github page](https://github.com/hyprland-community/pyprland). I had to install it from the AUR, because pip kept complaining about externally managed packages. I also tried using pipx for that matter, but it doesn't seem to work.

```
Traceback (most recent call last):
  File "/usr/bin/pypr", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/pyprland/command.py", line 171, in main
    asyncio.run(run_daemon() if len(sys.argv) <= 1 else run_client())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyprland/command.py", line 162, in run_client
    _, writer = await asyncio.open_unix_connection(CONTROL)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/streams.py", line 98, in open_unix_connection
    transport, _ = await loop.create_unix_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/unix_events.py", line 259, in create_unix_connection
    await self.sock_connect(sock, path)
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 642, in _sock_connect
    sock.connect(address)
```
I get this error when I manually try to run pypr toggle term. This is also the case with hpr-scratcher. I can see that processes are spawned, but i just can't seem to access the scratchpads. 
I also don't see pypr in btop after restarting. I do have the `exec-once` line in `hyprland.conf `

**Comment by ModestasStankus** [comment]
I have same issue.

**Comment by KSaiAkshit** [comment]
Just for clarification, what do you mean remove all pip-installed packages? I have quite a few packages, here is the out put for `pip list`: https://pastebin.com/QZc5J4cs
I did try installing it from AUR, in fact, that's how I did it at first. It didn't work either.

**Comment by fdev31** [comment]
By the way, I digressed with the pip problem.
Here pypr didn't start, you can remove everything from the hyprland config, and run manually in a terminal:

`DEBUG=1 pypr`

You'll have traces and pypr will run in the foreground in this window. I bet it's not starting, you'll see why (you can paste the content here).

**Comment by Gerzulet** [comment]
I have the same problem, if i run pypr on a terminal, and use the keyboard shortcuts (i.e. term scratchpad), it works fine, of course this means i must have the terminal open with pypr running, which defeats the purpose.  
Still havent tried reinstalling the python packages, although i installed this with yay.

**Comment by fdev31** [comment]
you can make a script which will log the error, I hope it will provide more useful information:
```
#!/bin/bash
DEBUG=1 pypr > /tmp/pypr.log
```

**Comment by fdev31** [comment]
I changed something in the master branch, fixing a race condition - it's also a possibility for this bug.
You might be interested in upgrading to the git version to test it in case you suffer from this problem.

**Comment by fdev31** [comment]
I added better error handling in master.
You can also log to a file using `--debug path_to_some_file.txt`.
On startup, run pypr with this flag so we can fetch the output easily.
When failing, I hope you'll get more comprehensible error message.

**Comment by fdev31** [comment]
Released version `1.4.0`,  hoping you'll get better debug output helping you understand this problem.
Error handling can still be improved, please share your feedback.
I'll close this bug until more details are provided, discarding an environment anomaly.

**Comment by Fasolovic** [comment]
> I wanted to setup some scratchpads, and i followed the guide on their [github page](https://github.com/hyprland-community/pyprland). I had to install it from the AUR, because pip kept complaining about externally managed packages. I also tried using pipx for that matter, but it doesn't seem to work.
> 
> ```
> Traceback (most recent call last):
>   File "/usr/bin/pypr", line 8, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "/usr/lib/python3.11/site-packages/pyprland/command.py", line 171, in main
>     asyncio.run(run_daemon() if len(sys.argv) <= 1 else run_client())
>   File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
>     return runner.run(main)
>            ^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/site-packages/pyprland/command.py", line 162, in run_client
>     _, writer = await asyncio.open_unix_connection(CONTROL)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/asyncio/streams.py", line 98, in open_unix_connection
>     transport, _ = await loop.create_unix_connection(
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/asyncio/unix_events.py", line 259, in create_unix_connection
>     await self.sock_connect(sock, path)
>   File "/usr/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
>     return await fut
>            ^^^^^^^^^
>   File "/usr/lib/python3.11/asyncio/selector_events.py", line 642, in _sock_connect
>     sock.connect(address)
> ```
> 
> I get this error when I manually try to run pypr toggle term. This is also the case with hpr-scratcher. I can see that processes are spawned, but i just can't seem to access the scratchpads. I also don't see pypr in btop after restarting. I do have the `exec-once` line in `hyprland.conf `

Use `pip check` to identify any missing or broken dependencies. I had to downgrade some packages.

**Comment by lightmon233** [comment]
> I wanted to setup some scratchpads, and i followed the guide on their [github page](https://github.com/hyprland-community/pyprland). I had to install it from the AUR, because pip kept complaining about externally managed packages. I also tried using pipx for that matter, but it doesn't seem to work.
> 
> ```
> Traceback (most recent call last):
>   File "/usr/bin/pypr", line 8, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "/usr/lib/python3.11/site-packages/pyprland/command.py", line 171, in main
>     asyncio.run(run_daemon() if len(sys.argv) <= 1 else run_client())
>   File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
>     return runner.run(main)
>            ^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/site-packages/pyprland/command.py", line 162, in run_client
>     _, writer = await asyncio.open_unix_connection(CONTROL)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/asyncio/streams.py", line 98, in open_unix_connection
>     transport, _ = await loop.create_unix_connection(
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/asyncio/unix_events.py", line 259, in create_unix_connection
>     await self.sock_connect(sock, path)
>   File "/usr/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
>     return await fut
>            ^^^^^^^^^
>   File "/usr/lib/python3.11/asyncio/selector_events.py", line 642, in _sock_connect
>     sock.connect(address)
> ```
> 
> I get this error when I manually try to run pypr toggle term. This is also the case with hpr-scratcher. I can see that processes are spawned, but i just can't seem to access the scratchpads. I also don't see pypr in btop after restarting. I do have the `exec-once` line in `hyprland.conf `

same issue. solved.
you should run pypr as server first, then when you run pypr you may get some error, for me it's "placement ...", then you should add "monitors" option in your pyprland.json file 
like this


    "monitors": {
        "placement": {
          "BenQ PJ": {
            "topOf": "VGA-1"
          }
        },
        "unknown": "wlrlui"
    }
