### ISSUE TITLE
[FEAT] Magnify: relative value; float value

### ISSUE THREAD

**Issue by fedoranvar** [hyprland-community/pyprland#71]
**Is your feature request related to a problem? Please describe.**
I want to bind zooming in/out to scroll wheel, like in web browser;
For more smoothing effect float value for zooming would be good

**Describe the solution you'd like**
Implementing relative value to zoom ;
implementing float value for zooming 

e.g. `pypr zoom +0.5`

**Describe alternatives you've considered**
with keybinding, changing value in file for runtime absolute zoom value  and pasting it into `pypr zoom <value>`

**Comment by fedoranvar** [comment]
found out, that i can solve this by using `misc:cursor_zoom_factor` in hyprland

**Comment by fdev31** [comment]
How did you manage to "increase" or "decrease" ?
It still sounds like something nice to add :)

**Comment by fdev31** [comment]
Check https://github.com/hyprland-community/pyprland/releases/tag/2.1.4 out ...
