### ISSUE TITLE
[BUG] hyprland does not interact with pypr

### ISSUE THREAD

**Issue by logexp1** [hyprland-community/pyprland#73]
**Pyprland version**
2.1.4-1

**Describe the bug**
Since I updated to version 2.1.4 and hyprland to 0.37 (and also tried with 0.38), hyprland does not launch  pyprland with `exec-once = pypr` when it starts.

When I open terminal and executes pypr from CLI, it launches. However, scratchpad does not work with shortcut  `bind = $super,	t,	exec, pypr toggle term`. Again, typing `pypr toggle term` from CLI launches scratchpad as expected.  

My other keybinding from hyprland works, too. Only executing pypr command is not responding. 

Thanks again for this wonderful package.

**Additional context**
I updated hyprland since I was changing `bind = $super, 1, workspace, 1` to `bind = $super, 1, focusworkspaceoncurrentmonitor, 1` Is this related?

**Comment by fdev31** [comment]
Hi, without any log I'll not be able to help...
Can you capture the output of the pypr instance started from hyprland.conf ? I hope it will give us some clues.

If you ensure pypr isn't running when you start it from the terminal, it can also help making it work.

**Comment by alekgr** [comment]
add this to  exec-once = pypr --debug /tmp/pypr.log to get logs

**Comment by logexp1** [comment]
When I initially tried `exec-once = pypr --debug /tmp/pypr.log`, log file was not created, so figured that hyprland can't locate pypr, so I inserted full path (`~/.local/bin/pypr`), now I can find pypr process is on after I log in.  Maybe it was due to change in hyprland..

I also fixed keybinding to have full path, and now it works as expected!

Thanks for the help!
