### ISSUE TITLE
[FEAT] Allow for different wallpapers on different monitors

### ISSUE THREAD

**Issue by phunni** [hyprland-community/pyprland#78]
As far as I can tell, the wallpapers plugin sets the wallpaper on multiple monitors to the same thing. I would like to be able to configure it to use a different image for each monitor.

**Describe the solution you'd like**
I would like to be able to configure it to use a different image for each monitor.

**Comment by fdev31** [comment]
Check the version 2.2.5 including such feature, sorry to break the existing syntax (in case you overloaded `command`) - but I already realized it may cause problems in the future.

**Comment by phunni** [comment]
Ah - thank you. I appear to only have 2.2.4 installed.

**Comment by fdev31** [comment]
> Ah - thank you. I appear to only have 2.2.4 installed.

I just posted the new version 1 hour ago, should be the same as git
