### ISSUE TITLE
[BUG] Configuration not read from `included` files

### ISSUE THREAD

**Issue by dantefromhell** [hyprland-community/pyprland#84]
**Pyprland version**
Which version did you use? (copy & paste the string returned by `pypr version`)

```
❯ pypr version
2.2.7
```

**Describe the bug**

Configuration settings in files added via the `include` config option are not added to overall configuration.

Example `~/.config/hypr/pyprland.toml`
```
[pyprland]
plugins = [ "scratchpads" ]
include = ["~/.config/overrides/pyprland/99__testing.toml"]

[scratchpads.kitty]
command = "kitty --class kitty-scratchpad"
lazy = false
size = "74% 60%"
position = "13% 7%"
alt_toggle = true
```

And file `/home/dante/.config/overrides/pyprland/99__testing.toml`
```
[scratchpads.betterbird]
command = "betterbird"
animation = "fromRight"
lazy = true
alt_toggle = true
```

Yields the following behaviour when manually toggling scratchpads
- `❯ pypr toggle kitty` working as expected
- `❯ pypr toggle betterbird` triggering an error message saying `Scratchpad betterbird not found`

**Comment by fdev31** [comment]
Having a single plugin spread into several files can be hard to predict and is then an implementation detail which I would not like have to describe and should be able to change in the future.
If you have all the scratchpads in one file does it work ?
