### ISSUE TITLE
Scratchpads don't work on non-default screen scales

### ISSUE THREAD

**Issue by askarbink** [hyprland-community/pyprland#9]
My laptop has a 14" display, so I have set the scale to the value 2. I can't get Pyprland to work correctly with this. I tried to configure a scratchpad with a dropterm just as in the README, but the terminal window spawns outside the screen. When I set the scale to 1, everything works just as intended, but I can't use this scale all the time.

UPD: The problem only occurs when an animation is set in `pyprland.json`.

**Comment by askarbink** [comment]
UPD: The problem only occurs when an animation is set.

**Comment by fdev31** [comment]
I confirm screen scaling isn't supported.
I'll try to have a look at this problem soon.

**Comment by fdev31** [comment]
Are you able to test the git version and confirm it works for you ?

**Comment by askarbink** [comment]
Yes, works perfectly, thank you!
