### ISSUE TITLE
[BUG] Invalid json data at pypr startup

### ISSUE THREAD

**Issue by JohnRTitor** [hyprland-community/pyprland#96]
**Pyprland version**
2.2.14-10

**Describe the bug**
pyprland shows invalid json data error when launched at startup.

**To Reproduce**
1. Launch `pypr` at startup using exec-once=pypr
2. Relogin
3. See the error

**Expected behavior**
No error.

**Configuration (provide following files/samples when relevant):**
- [pyprland.toml](https://pastebin.com/x3bK79Ka)
- hyprland.conf - My config is pretty heavy, though I am using 
```
# pyprland autostart
exec-once = pypr
```

**Additional context**
OS: NixOS
I am using the flake to get the git version.

![IMG_20240429_121214](https://github.com/hyprland-community/pyprland/assets/50095635/aac3d4b8-1434-467b-b4ed-fb04f0253864)

**Comment by fdev31** [comment]
How am I supposed to report this error then?
Shouldn't the nix package be fixed instead?

**Comment by JohnRTitor** [comment]
Yes. pyprland works as expected. This is likely a regression from [2.2.12](https://github.com/hyprland-community/pyprland/tree/2.2.12) after which the version check is added. I can confirm it works on 2.2.5.

And I am using pyprland from this repository's flake, not from nixpkgs.

**Comment by JohnRTitor** [comment]
Indeed, it seems so, checking `hyprctl version -j` shows 
```
{
    "branch": "",
    "commit": "b164e67d8b1f12420ec44a1c837af7923559ccf2",
    "dirty": false,
    "commit_message": "",
    "commit_date": "2024-04-28",
    "tag": "",
    "commits": @COMMITS@,
    "flags": []
}
```

**Comment by fdev31** [comment]
You can try to report a bug to the packager...

**Comment by JohnRTitor** [comment]
Should be fixed by https://github.com/hyprwm/Hyprland/commit/39595aaca3c16cc483dcaacdebaecc24c952246b
