### ISSUE TITLE
[BUG/cosmetic] Fail to parse hyprctl version

### ISSUE THREAD

**Issue by taschenlampe** [hyprland-community/pyprland#97]
**Pyprland Version**

 `2.2.15`

Pyprland is running smoothly in terms of functionality – no complaints there. But, I've noticed an error popping up in the startup logs about version parsing. It doesn't mess with the app's operation.

Here’s the error message:

`pyprland - Fail to parse hyprctl version: Expecting value: line 8 column 16 (char 136) // pyprland.py:18`

It's linked to this bit in the code:

`self.log.error("Fail to parse hyprctl version: %s", e)`

And here's a link to the full log for more context: [OpenSUSE Paste Link](https://paste.opensuse.org/pastes/e783254966de)

**Steps to Reproduce**

Just by firing up pypr 

Ideally, it’d be great if the app could start up without this little hiccup.

**Workaround** 

For now, I just nixed the version check by hardcoding:

`state.hyprland_version = VersionInfo(0, 0, 0)`

This stops the error from showing up, though I'm a bit worried it might cause issues down the road.
Cheers!

Almost forgot -> Thanks for all the awesome work on Pyprland! It’s a fantastic tool and I’m really enjoying using it. Keep up the great work!

**Comment by fdev31** [comment]
It looks like a duplicate of #96 - it turns to be a bug in Hyprland mainstram.

Problems shouldn't be hidden... this should happen in case of real issue either with Hyprland or with its packaging.

But first, what is the output of your `hyprctl -j version` ?

**Comment by fdev31** [comment]
Btw, I'm worried you needed a workaround, it should be "automatic", without it what happened wrong?

**Comment by taschenlampe** [comment]
Everything is functioning as expected with pypr.
 I've discovered a [bug](https://bugzilla.opensuse.org/show_bug.cgi?id=1218422) report relevant to my situation
