### ISSUE TITLE
[FEAT] Add `Anyrun` as `_menu` engine

### ISSUE THREAD

**Issue by morialo3** [hyprland-community/pyprland#99]
**Is your feature request related to a problem? Please describe.**
No problem acutally, I used to have `Rofi` installed, now I move to [anyrun](https://github.com/anyrun-org/anyrun), so to have a smooth transition to some features can be imported to `anyrun` so it can function the same way `Rofi` did.

**Describe the solution you'd like**
`anyrun` can function as `dmenu` through a plugin made for it. look here [README](https://github.com/anyrun-org/anyrun/blob/master/plugins/stdin/README.md) 

**Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
> Add any other context or screenshots about the feature request here.

**Comment by fdev31** [comment]
Keep in mind, the engine don't have to be supported most of the time, here you can just set

```toml
engine = "anyrun"
parameters = "--plugins libstdin.so"
```

I would have appreciated the command-line rather than checking it myself, but thank you for the ticket anyway!

**Comment by morialo3** [comment]
> I would have appreciated the command-line rather than checking it myself, but thank you for the ticket anyway!
Apologies for the *ugly* request format, maybe a format template would've helped, but any way  thank you very much.
